<font size = "3">

**(Q1)** Using the framework of a linked list (i.e., a data structure consisting of Nodes linked together), implement a `Stack` class. Proceed as follows:

1. Use the `Node` class from datasci531.py in your implementation.

2. Write a `Stack` class that is initialized (with `__init__`) the following attributes:

- `self._head = None` This serves the same purpose as in the `UnorderedList` class.

- `self._size = 0`. With this additional attribute, we can determine the size of the `Stack` without iterating through all of the nodes. Of course, we must update this attribute appropriately as we add/remove elements.

3. Define a `size` property that allows a user to determine the size of the `Stack`, but raises an error if they try to overwrite it. **Hint:** If you use the "@property" decorator and never define a function for setting the value, then it will raise an error when attempting to set it.

4. Implement the following methods, which should have the same effect as the original `Stack` we implemented using a Python list.

- `is_empty(self)`

- `push(self, item)`

- `pop(self)` Make sure to return the **value** stored in the Node, not the Node itself.

- `peek(self)` Make sure to return the **value** stored in the Node, not the Node itself.

5. Make sure all the methods listed above have $\mathcal{O}(1)$ complexity.

6. Make sure an appropriate error message is printed if someone tries to `pop` or `peek` from an empty Stack.

Feel free to change the name of the attribute `self._head` to `self._bottom` or `self._top` to make the connection to a Stack more explicit.

## Solution

In [1]:
from datasci531_hw2 import Node

class Stack:
    def __init__(self):
        self._head = None 
        self._size = 0

    def is_empty(self):
        return self._size == 0

    @property 
    def size(self):
        return self._size 

    def push(self, item):
        temp = Node(item)
        temp.next = self._head 
        self._head = temp
        self._size += 1

    def pop(self):
        if self.is_empty():
            raise IndexError("pop from empty stack")

        current = self._head 
        self._head = current.next
        self._size -= 1
        return current.data 

    def peek(self):
        if self.is_empty():
            raise IndexError("can't peek from empty stack")
        
        return self._head.data 

<font size = "3">

**(Q2)** Now, we will implement a **Queue** using the linked list framework.

1. Use the `Node` class from datasci531.py in your implementation.

2. Write a `Queue` class that is initialized (with `__init__`) the following attributes:

- `self._front = None` This is analogous to `self._head`.

- `self._rear = None` This is analogous to `self._head`, but points to the other end of the list

- `self._size = 0`. Same idea as the Stack class.

3. Create a `size` property that works the same way as the Stack.

4. Implement the following methods, which should have the same effect as the original `Queue` we implemented using a Python list.

- `is_empty(self)`

- `enqueue(self, item)`

- `dequeue(self)` Make sure to return the **value** stored in the Node, not the Node itself.

5. Make sure all the methods listed above have $\mathcal{O}(1)$ complexity. 

6. Make sure an appropriate error message is printed if someone tries to `dequeue` from an empty Queue.


## Solution

In [2]:
from datasci531_hw2 import Node

class Queue:
    def __init__(self):
        self._front = None 
        self._rear = None 
        self._size = 0 
    
    def is_empty(self):
        return self._size == 0

    @property 
    def size(self):
        return self._size 

    def enqueue(self, item):
        if self.is_empty():
            temp = Node(item)
            self._front = temp 
            self._rear = temp 
            self._size = 1
            return None 
        
        temp = Node(item)
        rear = self._rear 
        rear.next = temp
        self._rear = temp 
        self._size += 1

    def dequeue(self):
        if self.is_empty():
            raise IndexError("Can't dequeue from empty queue")

        if self._size == 1:
            current = self._front
            self._front = None 
            self._rear = None 
            self._size = 0
            return current.data

        current = self._front
        self._front = current.next 
        self._size -= 1
        return current.data 

<font size = "3">

**(Q3)** Now, we will implement a **Deque** using the linked list framework.

1. Write a `BiNode` class which extends the `Node` class by adding a `self._prev` attribute and a `prev` property.

2. Write a `Deque` class that is initialized (with `__init__`) the following attributes:

- `self._front = None`

- `self._rear = None`

- `self._size = 0`. Same idea as the Stack class.

3. Create a `size` property that works the same way as the Stack/Queue.

4. Implement the following methods, which should have the same effect as the original `Deque` we implemented using a Python list.

- `is_empty(self)`

- `add_front(self, item)`

- `remove_front(self)` Make sure to return the **value** stored in the Node, not the Node itself.

- `add_rear(self, item)`

- `remove_rear(self)` Make sure to return the **value** stored in the Node, not the Node itself.

5. Make sure all the methods listed above have $\mathcal{O}(1)$ complexity. 

6. Make sure an appropriate error message is printed if someone tries to remove an item from an empty Deque.

Feel free to use "left/right" instead of "front/rear" when defining your attributes and methods.


## Solution - BiNode class

In [ ]:
class BiNode:
    def __init__(self, node_data):
        if type(node_data) in [type({}), type(()), type([])]:
            raise ValueError("data should not be a data structure")
        self._data = node_data 
        self._next = None 
        self._prev = None 

    @property
    def data(self):
        """Get node data""" 
        return self._data 

    @data.setter
    def data(self, node_data):
        """Set node data""" 
        if type(node_data) in [type({}), type(()), type([])]:
            raise ValueError("data should not be a data structure")
        self._data = node_data 

    
    @property
    def next(self):
        """Get next node""" 
        return self._next 

    @next.setter 
    def next(self, node_next):
        """Set next node"""
        # should write test to make sure "node_next" is a node 
        if type(node_next) != type(self) and type(node_next) != type(None):
            raise ValueError("next should be another Node!")
        self._next = node_next 
    
    @property 
    def prev(self):
        return self._prev 

    @prev.setter 
    def prev(self, node_prev):
        """Set next node"""
        if type(node_prev) != type(self) type(node_next) != type(None):
            raise ValueError("next should be another Node!")
        self._prev = node_prev 

    def __str__(self):
        return str(self._data)

    def __repr__(self):
        return f"Node with value: {self._data}"

## Solution - Deque

In [4]:
class Deque:
    def __init__(self):
        self._front = None 
        self._rear = None 
        self._size = 0

    def is_empty(self):
        return self._size == 0

    @property
    def size(self):
        return self._size 

    def add_front(self, item):
        if self.is_empty():
            temp = BiNode(item)
            self._front = temp 
            self._rear = temp 
            self._size = 1
            return None

        temp = BiNode(item)
        current = self._front
        temp.next = current 
        current.prev = temp 
        self._front = temp 
        self._size += 1

    def remove_front(self):
        if self.is_empty():
            raise IndexError("Can't remove from empty deque")
        if self._size == 1:
            remove_node = self._front 
            self._front = None 
            self._rear = None 
            self._size = 0
            return remove_node.data

        remove_node = self._front 
        current = remove_node.next 
        current.prev = None 
        self._front = current 
        self._size -= 1
        return remove_node.data 

    def add_rear(self, item):
        if self.is_empty():
            temp = BiNode(item)
            self._front = temp 
            self._rear = temp 
            self._size = 1
            return None 
        
        temp = BiNode(item)
        current = self._rear 
        temp.prev = current 
        current.next = temp 
        self._rear = temp 
        self._size += 1

    def remove_rear(self):
        if self.is_empty():
            raise IndexError("Can't remove from empty deque")

        if self._size == 1:
            remove_node = self._rear 
            self._rear = None 
            self._front = None 
            self._size = 0
            return remove_node.data
            
        remove_node = self._rear 
        current = remove_node.prev 
        current.next = None 
        self._rear = current 
        self._size -= 1
        return remove_node.data

<font size = "3">

**(Q4)** The Knapsack problem - naive recursive solution

This is a classic combinatorial optimization problem. It's a common interview question, but also has applications to other decision-making processes like selection of assets and portfolios

We have a knapsack that has a carrying capacity of $W$ pounds. There are $n$ items, and for each $i \in \{1,2,\dots,n\}$ we define the parameters:

- $w_i$ is the weight of object $i$

- $v_i$ is the value of object $i$

- $x_i$ is 1 if we take the object (putting it into our knapsack), and 0 if we leave it

We want to maximize the value of the objects we take, but we are constrained by the fact that we can only hold $W$ pounds. Thus, we are led to the following constrained optimization problem:

- maximize $V = \sum_{i=1}^n v_ix_i$

- subject to the constraint $\sum_{i=1}^n w_ix_i \leq W$

Implement a "naive" (meaning inefficient) recursive solution to the problem by completing the code below.

**Hint:** For a given item, there are two possibilities: you either take it or leave it. So you can maximize the value for each possibility and compare them.


## Solution

In [5]:
def knapsack_rec(W, weights, values):
    n = len(weights)
    if sum(weights) <= W:
        return [1] * n
    if min(weights) > W:
        return [0] * n

    leave_first = [0] + knapsack_rec(W, weights[1:], values[1:])
    val_leave = sum([x*v for x,v in zip(leave_first, values)])

    if weights[0] > W:
        return leave_first 

    keep_first = [1] + knapsack_rec(W - weights[0], weights[1:], values[1:])
    val_keep = sum([x*v for x,v in zip(keep_first, values)])

    if val_keep >= val_leave:
        return keep_first 
    
    return leave_first

W = 6
weights = [5, 2, 2, 2]
values = [10, 4, 3, 4]

x = knapsack_rec(W, weights, values)
x_sol = [0, 1, 1, 1]

print(x)

[0, 1, 1, 1]


<font size = "3">

**(Q5)** The Knapsack problem - bottom-up dynamic programming solution

Implement a "bottom-up" dynamic programming solution to the Knapsack problem. You will need a two-dimensional "cache" with $n+1$ rows and $W+1$ columns.

In this case, for $0\leq i\leq n$ and $0 \leq j\leq W$, the entries of the cache will correspond to:

- $V[i,j] = $ the maximum possible value when only considering the first $i$ items, and having a knapsack with carrying capacity of $j$ pounds.

The solution to the problem is then $V[n, W]$ (all $n$ items with actual carrying capacity).


## Solution

In [ ]:
import numpy as np 

def knapsack_dp(W, weights, values):
    n = len(weights)
    V = np.zeros((n+1, W+1))

    for i in range(1, n+1):
        w, v = weights[i-1], values[i-1]
        for cap in range(1, W+1):
            V[i,cap] = V[i-1,cap]
            if w <= cap:
                V[i,cap] = max(V[i,cap], v + V[i-1, cap-w])

    # Reconstruct selection
    selection = [0]*n
    cap = W
    for i in range(n, 0, -1):
        if V[i,cap] != V[i-1,cap]:
            selection[i-1] = 1
            cap -= weights[i-1]

    # probably best to return the array "V" too
    return selection, V

In [10]:
W = 6
weights = [5, 2, 2, 2]
values = [10, 4, 3, 4]

x, V = knapsack_dp(W, weights, values)

# The true solution for this choice of arguments is:
x_sol = [0, 1, 1, 1]

print(x)
print()
print(V)

[0, 1, 1, 1]

[[ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0. 10. 10.]
 [ 0.  0.  4.  4.  4. 10. 10.]
 [ 0.  0.  4.  4.  7. 10. 10.]
 [ 0.  0.  4.  4.  8. 10. 11.]]
